export const temperatureData = [
  { id: "Andaman & Nicobar Island", value: 28 },
  { id: "Andhra Pradesh", value: 33 },
  { id: "Arunachal Pradesh", value: 18 },
  { id: "Assam", value: 26 },
  { id: "Bihar", value: 31 },
  { id: "Chandigarh", value: 30 },
  { id: "Chhattisgarh", value: 32 },
  { id: "Dadra & Nagar Haveli", value: 30 },
  { id: "Daman & Diu", value: 30 },
  { id: "Delhi", value: 32 },
  { id: "Goa", value: 29 },
  { id: "Gujarat", value: 34 },
  { id: "Haryana", value: 32 },
  { id: "Himachal Pradesh", value: 15 },
  { id: "Jammu & Kashmir", value: 10 },
  { id: "Jharkhand", value: 31 },
  { id: "Karnataka", value: 30 },
  { id: "Kerala", value: 29 },
  { id: "Lakshadweep", value: 29 },
  { id: "Madhya Pradesh", value: 34 },
  { id: "Maharashtra", value: 33 },
  { id: "Manipur", value: 24 },
  { id: "Meghalaya", value: 22 },
  { id: "Mizoram", value: 25 },
  { id: "Nagaland", value: 23 },
  { id: "Odisha", value: 32 },
  { id: "Puducherry", value: 31 },
  { id: "Punjab", value: 31 },
  { id: "Rajasthan", value: 35 },
  { id: "Sikkim", value: 16 },
  { id: "Tamil Nadu", value: 32 },
  { id: "Telangana", value: 33 },
  { id: "Tripura", value: 28 },
  { id: "Uttar Pradesh", value: 33 },
  { id: "Uttarakhand", value: 20 },
  { id: "West Bengal", value: 30 },
];